config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registraions: 'users/registrations' }
  root to: "recipes#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  get "favourites", to: "pages#favourites"

  resources :recipes, only: [:index, :show] do
    resources :favourites, only: [:create, :edit, :update]
  end
  resources :ingredients, only: [:show] do
    resources :ingredient_reviews, only: [:create, :update, :edit, :destroy, :index]
    resources :ingredient_shops, only: [:new, :create]
    resources :shops, only: [:new, :create]
  end



  get "aboutglobcipe", to: "pages#aboutglobcipe"
  get "meetteam", to: "pages#meetteam"

  resources :favourites, only: [:destroy]


end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients

  has_many :favourites, dependent: :destroy

  validates :name, :instruction, :category, :area, presence: true
  validates :name, uniqueness: true

  geocoded_by :area
  after_validation :geocode, if: :will_save_change_to_area?
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    area = params[:search].nil? ? nil : params[:search][:area].capitalize
    category = params[:search].nil? ? nil : params[:search][:category].capitalize

    if area.nil? && category.nil?
      @recipes = category_driven_recipes
    elsif area.present? && category.present?
      @recipes = Recipe.where(area: area, category: category)
    elsif area.present?
      @recipes = Recipe.where(area: area)
    elsif category.present?
      @recipes = Recipe.where(category: category)
    else
      @recipes = category_driven_recipes
    end
  end

  def show
    @recipe = Recipe.find(params[:id])
    @favourite = Favourite.new
    # @ingredient = Ingredient.find(params[:ingredient_id])
  end

  private

  def category_driven_recipes
    categories = ['Beef', 'Breakfast', 'Chicken', 'Dessert', 'Goat', 'Lamb', 'Miscellaneous', 'Pasta', 'Pork',
                  'Seafood', 'Side', 'Starter', 'Vegan', 'Vegetarian']
    recipes_truncated = []
    categories.each do |category|
      recipes_category_specific = Recipe.where(category: category)
      recipe_category_specific_random = recipes_category_specific[0]
      recipes_truncated << recipe_category_specific_random
    end
    recipes_truncated << Recipe.last
    recipes_truncated << Recipe.find_by(id: Recipe.last.id - 1)
    return recipes_truncated
  end

  def search_params
    return false if params[:search].nil?

    params.require(:search).permit(:area, :category)
  end
end

app/views/recipes/index.html.erb
<div class="banner-category " style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path('bannerHome.jpg') %>)">
  <h1 class="fw-bold fs-2">Welcome to <span class="website-name fs-1">Globcipe</span></h1>
  <h2 class="fw-bold fs-2">Bringing the Flavours of Home to Your Kitchen No Matter Where You Are</h2>
</div>
<%= simple_form_for :search, url: recipes_path, method: "GET", html: { class: 'row g-3 align-items-center' } do |f| %>
  <div class="col-md-5">
    <%= f.input :area, label: false, input_html: {class: "form-control", value: ""}, placeholder: "Countries: France, China, etc." %>
  </div>
  <div class="col-md-5">
    <%= f.input :category, label: false, input_html: {class: "form-control", value: ""}, placeholder: "Category: Beef, Vegetarian, etc." %>
  </div>
  <div class="col-md-2">
    <%= f.submit "Explore", class: "general-button mb-5 mt-4 w-100" %>
  </div>
<% end %>

<h2 class="body-headline">Globcipes of the day</h2>
<div class="grid-container">
  <% @recipes.each do |recipe| %>
    <div class="card">
      <div class="card-img">
        <%= link_to recipe_path(recipe) do %>
          <%= image_tag(recipe.image_url, width: 80, height: 80, alt: recipe.name) %>
        <% end %>
      </div>

      <div class="card-body">
        <p class="fs-5 fw-bold"><%= recipe.name %></p>
        <p><%= recipe.category %></p>
        <p><%= recipe.area %></p>
      </div>
      <%= link_to 'Details', recipe_path(recipe), class: "details-button" %>
    </div>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div class="banner-category banner-category-size" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path('bannerRecipes.jpg') %>)">
  <h1 class="fw-bold"><%= @recipe.name %></h1>
  <h2 class="fw-bold">Recipe</h2>
</div>
<div class="recipe-card">
  <div class="recipe-header">
    <h1><%= @recipe.name%></h1>
    <p><%= @recipe.area%> <%= @recipe.category%></p>
    <div class="recipe-image">
      <%= image_tag @recipe.image_url, alt: @recipe.name %>
    </div>
  </div>

<div class="ingredients-section">
  <h2>Ingredients</h2>
  <table>
    <tr>
      <th></th>
      <th style="width: 60px;"></th> <!-- Gap Column -->
      <th></th>
    </tr>

    <% # Get the ingredients and split them into two groups %>
    <% column1 = @recipe.recipe_ingredients.first(10) %>
    <% column2 = @recipe.recipe_ingredients.drop(10) %>

    <% # Determine the maximum number of rows %>
    <% max_rows = [column1.size, column2.size].max %>

    <% # Loop through the maximum number of rows and render ingredients in each column %>
    <% max_rows.times do |i| %>
      <tr>
        <td>
          <% if column1[i] %>
            <%= link_to column1[i].ingredient.name, ingredient_path(column1[i].ingredient.id), class: "links" %>
            <%= column1[i].measure %>
          <% end %>
        </td>

        <!-- Empty middle column to create a gap -->
        <td style="width: 50px;"></td>

        <td>
          <% if column2[i] %>
            <%= link_to column2[i].ingredient.name, ingredient_path(column2[i].ingredient.id), class: "links" %>
            <%= column2[i].measure %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

  <div class="instructions-section">
    <h2>Instructions</h2>
      <p><%= @recipe.instruction %> </p>
    <div class="video-section">
      <iframe width="808" height="616"src=<%= @recipe.embedded_youtube_url %>></iframe>
      <%# 640 480 %>
  </div>
  </div>
</div>
<%# Recipe Deatils section %>

<div class="recipe-card">
  <div class="recipe-header padding-bottom-card">
    <h1>Favourite it!</h1>
  </div>
  <div class="instructions-section padding-bottom-card">
    <% favourited = @recipe.favourites.find_by(user: current_user) %>

  <% if favourited.present?  %>
      <p>Favourited!</p>
      <p><%= favourited.remarks%> </p>
  <% else %>
    <%= simple_form_for [@recipe, @favourite], html: { class: "inline-form" } do |f| %>
      <%= f.input :remarks, input_html: { class: "inline-input form-control" }, placeholder: "Add a comment" %>
      <%= f.submit "Add me to Favourite", class: "general-button" %>
    <% end %>
  <% end %>
  </div>
</div>