config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registraions: 'users/registrations' }
  root to: "recipes#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  get "favourites", to: "pages#favourites"

  resources :recipes, only: [:index, :show] do
    resources :favourites, only: [:create, :edit, :update]
  end
  resources :ingredients, only: [:show] do
    resources :ingredient_reviews, only: [:create, :update, :edit, :destroy, :index]
    resources :ingredient_shops, only: [:new, :create]
    resources :shops, only: [:new, :create]
  end



  get "aboutglobcipe", to: "pages#aboutglobcipe"
  get "meetteam", to: "pages#meetteam"

  resources :favourites, only: [:destroy]


end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer ">
  <div class="container">
    <div class="footer-left">
      <h2 class="footer-title">Globcipe</h2>
    </div>

    <div class="footer-center">
      <span class="follow-us">Follow Us</span>
      <a href="#" class="social-icon">
        <i class="fab fa-instagram fa-xl"></i>
      </a>
      <a href="#" class="social-icon">
        <i class="fab fa-twitter fa-xl"></i>
      </a>
      <a href="#" class="social-icon">
        <i class="fab fa-github fa-xl"></i>
      </a>
      <a href="#" class="social-icon">
        <i class="fab fa-facebook fa-xl"></i>
      </a>
    </div>

    <div class="footer-right">
      <%= link_to "Meet the team", meetteam_path, class: "general-button" %>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid container">
    <%= link_to recipes_path, class: "navbar-brand" do %>
      <%= image_tag 'globcipe-logo.png' %>
      <span class="name"> Globcipe</span>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", recipes_path, class: "general-button" %>
          </li>
          <li class="nav-item active">
            <%= link_to "About", aboutglobcipe_path, class: "general-button" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag 'DamienBaubriau.jpg', class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Your favourites", favourites_path , class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>