config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registraions: 'users/registrations' }
  root to: "recipes#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  get "favourites", to: "pages#favourites"

  resources :recipes, only: [:index, :show] do
    resources :favourites, only: [:create, :edit, :update]
  end
  resources :ingredients, only: [:show] do
    resources :ingredient_reviews, only: [:create, :update, :edit, :destroy, :index]
    resources :ingredient_shops, only: [:new, :create]
    resources :shops, only: [:new, :create]
  end



  get "aboutglobcipe", to: "pages#aboutglobcipe"
  get "meetteam", to: "pages#meetteam"

  resources :favourites, only: [:destroy]


end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :ingredient_reviews
  has_many :recipes, through: :ingredient_reviews

  has_many :ingredient_shops
  has_many :shops, through: :ingredient_shops

  has_many :substitutes

  validates :name, presence: true
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def show
    @ingredient = Ingredient.find(params[:id])

    @substitutes = Substitute.where(ingredient_id: params[:id])

    @ingredient_review = IngredientReview.new

    # map
    @shops = @ingredient.shops
    # The `geocoded` scope filters only flats with coordinates
    @shopmarkers = @shops.map do |shop|
      {
        lat: shop.latitude,
        lng: shop.longitude,
        # info_window_html: render_to_string(partial: "info_window", locals: { shop: shop })
        info_window: render_to_string(partial: "popup", locals: {shop: shop}),
        image_url: helpers.asset_url("glocipe-logo.png")

      }
    end
  end
end

app/views/ingredients/_info_window.html.erb
<h2><%= shop.name %></h2>
<p><%= shop.address %></p>

app/views/ingredients/_popup.html.erb
<h2><%= shop.name %></h2>
<p><%= shop.address %></p>

app/views/ingredients/show.html.erb
<div class="banner-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= image_path('bannerIngredients.jpg') %>)">
  <h1 class="fw-bold"><%= @ingredient.name %></h1>
  <h2 class="fw-bold">Ingredient</h2>
</div>

<div class="recipe-card pb-4">
  <div class="recipe-header pb-3">
    <h1><%= @ingredient.name %></h1>
    <div class="ingredients-image">
      <%= image_tag("https://www.themealdb.com/images/ingredients/#{@ingredient.name}.png", alt: @ingredient.name) %>
    </div>
  </div>

  <div class="ingredients-section padding-ingredients">
    <h2>Possible substitutions</h2>
    <ul class="ingredients-list">
    <% @ingredient.substitutes.each do |substitute|%>
      <li><%= substitute.name%> </li>
    <%end%>
      <li class="li-amazon"> You can order <%=@ingredient.name%> on:
      <div class="amazon-button">
        <%= link_to "Amazon", "https://www.amazon.com/s?k=#{@ingredient.name}&crid=33F8WONUCWOEO&sprefix=%2Caps%2C188&ref=nb_sb_noss", class: "btn btn-primary", target: "_blank", rel: "noopener noreferrer" %>
      </div>
      </li>
    </ul>
  </div>

</div>

<div class="recipe-card pb-4">
  <div class="recipe-header padding-bottom-card ">
    <h1>Find shops available in the UK</h1>
  </div>
  <div class="video-section m-4" style="width: 980; height: 616px;"
    data-controller="map"
    data-map-markers-value="<%= @shopmarkers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
  <div class="instructions-section">
    <p>You can also add your shop manually <%= link_to 'Add Shop', new_ingredient_ingredient_shop_path(@ingredient), class:"general-button" %></p>
  </div>
</div>

<div class="recipe-card pb-4">
  <div class="recipe-header padding-bottom-card ">
    <h1>Add a comment</h1>
  </div>
<div class="instructions-section">
  <%= simple_form_for [@ingredient, @ingredient_review], html: { class: "inline-form" } do |f| %>
    <%= f.input :comment, input_html: { class: "inline-input" }, placeholder: "Add a comment", label: false %>
    <%= f.submit "Submit your comment", class: "general-button mb-3" %>
  <% end %>
</div>

<ul>
  <% @ingredient.ingredient_reviews.each do |review| %>
    <div>
      <div data-controller="toggle" class="padding-right-card">
        <i class="fa-solid fa-comment mt-2"></i> <%= review.user.username %>: "<%= review.comment %>"
        <% if review.user == current_user %>
          <%= link_to ingredient_ingredient_review_path(review.comment, review), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
            <i class="fa-solid fa-trash text-dark"></i>
          <% end %>
          <button class="icon-button" data-action="click->toggle#fire">
            <i class="fa-solid fa-pen-to-square edit-btn text-dark"></i>
          </button>
          <div data-toggle-target="togglableElement" class="d-none">
            <%= simple_form_for [@ingredient, review], html: { class: "inline-form" } do |f| %>
              <%= f.input :comment, input_html: { class: "inline-input form-control" }, label: false %>
              <%= f.submit "Submit Edit", class: "general-button" %>
            <% end %>
          </div>
        <% else %>
          <%= " " %>
        <% end %>
      </div>
    </div>
  <% end %>
</ul>
</div>