config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registraions: 'users/registrations' }
  root to: "recipes#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  get "favourites", to: "pages#favourites"

  resources :recipes, only: [:index, :show] do
    resources :favourites, only: [:create, :edit, :update]
  end
  resources :ingredients, only: [:show] do
    resources :ingredient_reviews, only: [:create, :update, :edit, :destroy, :index]
    resources :ingredient_shops, only: [:new, :create]
    resources :shops, only: [:new, :create]
  end



  get "aboutglobcipe", to: "pages#aboutglobcipe"
  get "meetteam", to: "pages#meetteam"

  resources :favourites, only: [:destroy]


end

app/views/pages/_popup.html.erb
<h2><%= link_to recipe.name, recipe_path(recipe), class: "fav_map_link" %></h2>
<p><%= recipe.category %></p>

app/views/pages/aboutglobcipe.html.erb
<div class="banner-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path('bannerHome.jpg') %>')">
  <h1 class="fw-bold">About</h1>
</div>
<div class="about_text text-center">
  <p>Welcome to Globcipe, a great app for finding recipes from around the world designed for home cooking enthusiasts.</p>
  <p>Are you looking for inspiration or want to find a recipe based on certain ingredient or from a specific cuisine or a combination of both? </p>
  <p>Globcipe offers a wide array of recipes including a detailed ingredient list and cooking instructions.</p>
  <p>A very useful feature of Globcipe is an integrated ingredient substitution list for each ingredient. </p>
  <p>So if you are missing an ingredient or can't get it in your area, don't worry the app can offer you suggestions on what to replace it with.</p>
  <p>Remember to have fun and cook away!</p>
</div>

<div class="d-flex align-content-center justify-content-center">
  <div>
    <%= image_tag "utensil.jpg" %>
  </div>
  <div>
    <%= image_tag "utensil.jpg" %>
  </div>
</div>

app/views/pages/favourites.html.erb
<div class="banner-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path('bannerHome.jpg') %>')">
  <h1 class="fw-bold">Your Favourites</h1>
</div>
<div class="d-flex">
  <div class="grid-container-favourite">
    <% @favourites.each do |favourite| %>
      <div class="card" id="favourite_card">
        <div class="card-img">
          <%= link_to recipe_path(favourite.recipe) do %>
            <%= image_tag(favourite.recipe.image_url, width: 80, height: 80, alt: favourite.recipe.name) %>
          <% end %>
        </div>

        <div class="card-body position-relative">
          <p class="fs-5 fw-bold"><%= favourite.recipe.name %></p>
          <p><%= favourite.recipe.category %></p>
          <p><%= favourite.recipe.area %></p>
          <%= link_to favourite_path(favourite), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
            <i class="fa-solid fa-trash text-dark position-absolute bottom-0 end-6"></i>
          <% end %>
        </div>
        <%= link_to 'Details', recipe_path(favourite.recipe), class: "details-button" %>
      </div>
    <% end %>
  </div>
  <div class="mt-4 mb-5" id="map"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/meetteam.html.erb
<div class="banner-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path('bannerHome.jpg') %>')">
  <h1 class="fw-bold">The Team</h1>
</div>
<div class="profile_container">
  <div class="founders-card">
    <div>
      <%= image_tag("founder01.jpeg", class: "founders-card-img") %>
    </div>
    <div>
      <h2>Claudia Kwok</h2>
      <h3>Software Engineer</h3>
      <h4>UK</h4>
      <p>Aspiring to drive product development through people-centered AI solutions that deliver meaningful, positive impact.</p>
    </div>
  </div>

  <div class="founders-card">
    <div>
      <%= image_tag("founder02.jpeg", class: "founders-card-img") %>
    </div>
    <div>
      <h2>Damien Baubriau</h2>
      <h3>Software Engineer</h3>
      <h4>UK</h4>
      <p>Transitioning to Full-Stack Development, I leverage my sales experience, technical skills, and problem-solving mindset to grow as a software developer while applying my customer-focused approach to web development.</p>
    </div>
  </div>

  <div class="founders-card">
    <div>
      <%= image_tag("founder03.jpeg", class: "founders-card-img") %>
    </div>
    <div>
      <h2>Szymon Niedorezo</h2>
      <h3>Software Engineer</h3>
      <h4>UK</h4>
      <p>Hello I'm Simon. Aspiring web developer based in Cornwall.</p>
    </div>
  </div>

  <div class="founders-card">
    <div>
      <%= image_tag("founder04.jpeg", class: "founders-card-img") %>
    </div>
    <div>
      <h2>Joshua Banjo</h2>
      <h3>Software Engineer</h3>
      <h4>UK</h4>
      <p>Backend Engineer with a product focus and passion for building robust, scalable APIs in high growth start ups.</p>
    </div>
  </div>
</div>